class Constants:
    # WIDGETS
    REFERENCE_WINDOW_WIDTH = 1366
    REFERENCE_WINDOW_HEIGHT = 768

    REFERENCE_BATTLE_LIST_WIDGET_HEIGHT = 180
    REFERENCE_STAT_WIDGET_ANCHOR_TO_START_NUMBER = 110
    REFERENCE_STAT_WIDGET_ANCHOR_TO_END_NUMBER = 150
    REFERENCE_GAME_WIDGET_X_ANCHOR_TO_START_NUMBER = 140
    REFERENCE_GAME_WIDGET_X_ANCHOR_TO_END_NUMBER = 135
    REFERENCE_GAME_WIDGET_Y_ANCHOR_TO_END_NUMBER = 542

    REFERENCE_PLAYER_TO_LOOT_PIXELS = 44

    # APP MODE
    TRAIN_MODE = "TRAIN_MODE"
    DEBUG_MODE = "DEBUG_MODE"
    DEV_MODE = "DEV_MODE"

    # GAME
    MIN_MANA_SURPLUS = 10
    MAX_MANA_SURPLUS = 100

    MIN_EAT_TIMES = 1
    MAX_EAT_TIMES = 4

    MIN_MINUTES_WITHOUT_FOOD = 5
    MAX_MINUTES_WITHOUT_FOOD = 12

    # SPELLS
    LIGHT_HEALING = "exura infir ico"
