class Constants:
    REFERENCE_WINDOW_WIDTH = 1366
    REFERENCE_WINDOW_HEIGHT = 768

    REFERENCE_BATTLE_LIST_WIDGET_HEIGHT = 180
    REFERENCE_STAT_WIDGET_ANCHOR_TO_START_NUMBER = 110
    REFERENCE_STAT_WIDGET_ANCHOR_TO_END_NUMBER = 150
